
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 26 20:38:12 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 33;
  public static final int DIVIDE = 29;
  public static final int INCREMENT = 46;
  public static final int CONST = 6;
  public static final int PARENTHESES_BEGIN = 12;
  public static final int EQUALS = 39;
  public static final int NOT_EQUAL = 40;
  public static final int SEMI = 25;
  public static final int CONTINUE = 23;
  public static final int NUM_CONST = 32;
  public static final int DECREMENT = 37;
  public static final int MINUS = 27;
  public static final int AND = 45;
  public static final int RECORD = 51;
  public static final int OR = 44;
  public static final int COMMA = 36;
  public static final int CLASS = 7;
  public static final int LESS_EQUAL = 43;
  public static final int BRACKET_END = 10;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 28;
  public static final int ASSIGN = 47;
  public static final int BRACES_BEGIN = 4;
  public static final int IF = 18;
  public static final int THIS = 50;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int PARENTHESES_END = 9;
  public static final int SUPER = 48;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MODULO = 30;
  public static final int BREAK = 22;
  public static final int IDENT = 3;
  public static final int VOID = 16;
  public static final int BRACES_END = 5;
  public static final int COLON = 17;
  public static final int ELSE = 19;
  public static final int BRACKET_BEGIN = 11;
  public static final int ENUM = 49;
  public static final int READ = 13;
  public static final int GOTO = 26;
  public static final int LARGER_EQUAL = 38;
  public static final int WHILE = 21;
  public static final int LARGER_THAN = 41;
  public static final int EXTENDS = 8;
  public static final int BOOL_CONST = 34;
  public static final int LESS_THAN = 42;
  public static final int PRINT = 14;
  public static final int DO = 20;
}

