
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 18 17:32:30 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int PROG = 1;
  public static final int BREAK = 2;
  public static final int CLASS = 3;
  public static final int ENUM = 4;
  public static final int ELSE = 5;
  public static final int CONST = 6;
  public static final int IF = 7;
  public static final int DO = 8;
  public static final int WHILE = 9;
  public static final int NEW = 10;
  public static final int PRINT = 11;
  public static final int READ = 12;
  public static final int RETURN = 13;
  public static final int VOID = 14;
  public static final int EXTENDS = 15;
  public static final int CONTINUE = 16;
  public static final int THIS = 17;
  public static final int SUPER = 18;
  public static final int GOTO = 19;
  public static final int RECORD = 19;
  
  
  
  public static final int PLUS = 19;
  public static final int MINUS = 20;
  public static final int MULTIPLY = 21;
  public static final int DIVIDE = 22;
  public static final int MODULO = 23;
  public static final int EQUALS = 24;
  public static final int NOT_EQUAL =25;
  public static final int LARGER_THAN = 26;
  public static final int LARGER_EQUAL = 27;
  public static final int LESS_THAN = 28;
  public static final int LESS_EQUAL = 29;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int ASSIGN = 32;
  public static final int INCREMENT = 33;
  public static final int DECREMENT = 34;
  public static final int SEMI = 35;
  public static final int COLON = 36;
  public static final int COMMA = 37;
  public static final int DOT = 38;
  public static final int PARENTHESES_BEGIN = 39;
  public static final int PARENTHESES_END = 40;
  public static final int BRACES_BEGIN = 41;
  public static final int BRACES_END = 42;
  public static final int BRACKET_BEGIN = 43;
  public static final int BRACKET_END = 44;
  public static final int COMMENT = 45;
  
  
  public static final int BOOL_CONST = 46;
  public static final int NUM_CONST = 47;
  public static final int IDENT = 48;
  public static final int CHAR_CONST = 49;

}

